# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

host: localhost


development:
  adapter: postgresql
  encoding: unicode
  database: mettleme_development
  pool: 5
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: mettleme_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: mettleme_production
  pool: 5

